### ISSUE TITLE
[BUG]: Guice is not initialized

### ISSUE THREAD

**Issue by doanguyen** [pmoscode-helm/axelor-open-suite-docker#13]
### Description of the bug

Version used:
- axelor: v6.5.17

Tomcat can't fired up and here is the log

```log
23-Sep-2023 21:09:04.398 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [com.axelor.web.AppContextListener]
	com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/xml/ws/Service
		at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
		at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
		at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
		at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
		at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
		at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
		at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
		at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
		at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:581)
		at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:176)
		at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
		at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
		at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
		at com.google.inject.Guice.createInjector(Guice.java:87)
		at com.google.inject.Guice.createInjector(Guice.java:69)
		at com.google.inject.Guice.createInjector(Guice.java:59)
		at com.axelor.web.AppContextListener.getInjector(AppContextListener.java:110)
		at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
		at com.axelor.web.AppContextListener.contextInitialized(AppContextListener.java:49)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4441)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4899)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:710)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:687)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/xml/ws/Service
		at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
		at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
		at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
		at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
		at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
		at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
		at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
		at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:74)
		at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
		at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
		at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
		at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
		at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
		at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
		at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
		at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
		... 31 more
	Caused by: java.lang.NoClassDefFoundError: javax/xml/ws/Service
		at java.base/java.lang.Class.getDeclaredFields0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
		at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
		at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:760)
		at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:670)
		at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
		at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:182)
		at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:661)
		at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:617)
		at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:603)
		at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932)
		at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
		at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
		at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
		at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:39)
		at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:126)
		at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93)
		at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:36)
		at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
		at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:41)
		at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
		at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
		at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
		at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
		at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
		... 46 more
	Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Service
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1420)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1228)
		... 71 more
23-Sep-2023 21:09:04.440 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [com.axelor.web.AppContextListener]
	java.lang.RuntimeException: Guice is not initialized.
		at com.axelor.inject.Beans.get(Beans.java:45)
		at com.axelor.inject.Beans.get(Beans.java:58)
		at com.axelor.meta.loader.ViewWatcher.getInstance(ViewWatcher.java:128)
		at com.axelor.web.AppContextListener.contextDestroyed(AppContextListener.java:102)
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4487)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5127)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:175)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:710)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:687)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by pmoscode** [comment]
Hi @doanguyen,
thanks for the bug report.
Did you try the v7* version? 

This is the one I use for myself and it is working.

Do you need to use v6?

**Comment by pmoscode** [comment]
I tested it and it seems, that v6.* is not compatible with tomcat 10.*

And in addition to that, it seems that Axelor is not respecting the environment variables (like v7), which is described here:
https://docs.axelor.com/adk/6.1/dev-guide/application/config.html#database-settings
It could not connect to the database. It used the wrong (probably default) DB_URL. 

I will do some more tests.

The official Axelor documentation is very incomplete. (my own opinion)
So that, the docs from above are referencing v6.1 but they seems not to apply to > v6.1 (I'm testing with v6.5.17)
But for v7 they are working. That is more than strange.

Anyway, if v6 won't work in my tests, I will focus on v7 only and remove all v6 versions from Dockerhub..

**Comment by pmoscode** [comment]
v6 is not working, so I will remove all versions from Dockerhub.

**Comment by pmoscode** [comment]
Is it ok for you, when I close this issue? @doanguyen
